from typing import Optional, Protocol, Sequence
from .types import HandshakeContext, PendingSession, SessionKeys

class AlgorithmProvider(Protocol):
    suite: str
    def seal(self, key: bytes, nonce: bytes, aad: bytes, plaintext: bytes) -> bytes: ...
    def open(self, key: bytes, nonce: bytes, aad: bytes, ciphertext: bytes) -> bytes: ...
class KeyProvider(Protocol):
    async def find_session(self, key_id: str, session_id: str) -> Optional[SessionKeys]: ...
class SessionRepository(KeyProvider, Protocol):
    async def save_pending(self, value: PendingSession) -> None: ...
    async def find_pending(self, key_id: str, session_id: str) -> Optional[PendingSession]: ...
    async def activate(self, key_id: str, session_id: str) -> None: ...
    async def remove(self, key_id: str, session_id: str) -> None: ...
class ReplayProtector(Protocol):
    async def claim(self, session_id: str, direction: str, sequence: int, ttl_seconds: float) -> bool: ...
class InstallationRegistry(Protocol):
    async def find(self, app_id: str, device_id: str) -> Optional[bytes]: ...
    async def register(self, app_id: str, device_id: str, device_type: str, public_key: bytes) -> None: ...
class EnrollmentTokenService(Protocol):
    async def issue(self, app_id: str, device_type: str, ttl_seconds: float) -> str: ...
    async def consume(self, token: str, app_id: str, device_id: str, device_type: str) -> None: ...
class HandshakeAuthorizer(Protocol):
    async def authorize(self, context: HandshakeContext) -> None: ...
class LogicalRouteAuthorizer(Protocol):
    def is_allowed(self, method: str, path: str) -> bool: ...
class ServerIdentityProvider(Protocol):
    @property
    def key_id(self) -> str: ...
    @property
    def encoded_public_key(self) -> bytes: ...
    def sign_transcript(self, transcript_hash: bytes) -> bytes: ...
class SessionRecordProtector(Protocol):
    def protect(self, plaintext: bytes) -> bytes: ...
    def unprotect(self, protected_record: bytes) -> bytes: ...
class SecurityPolicy(Protocol):
    require_tls: bool
    allowed_suites: Sequence[str]
    clock_skew_seconds: float
    replay_ttl_seconds: float
    max_envelope_bytes: int
    max_plaintext_bytes: int
    max_body_bytes: int
